{{- $fullName := include "fullName" . -}}
{{- $namespace := include "namespace" . -}}
{{- $maxCount := include "maxCount" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  namespace: {{ $namespace }}
  labels:
    helmVersion: {{ .Chart.Version }}
    helmAppVersion: {{ .Chart.AppVersion }}
    helmName: {{ .Chart.Name }}
  annotations:
    cert-manager.io/cluster-issuer: {{ $fullName }}-issuer
spec:
  ingressClassName: {{ .Values.ingress.className }}
  tls:
  - hosts:
    - {{ include "hostName" . }}
    secretName: {{ include "ingress.tls.secretName" . }}
  rules:
  - host: {{ include "hostName" . }}
    http:
      paths:
      {{- range $i, $e := until (int $maxCount) }}
        - path: /{{ $i }}
          pathType: Prefix
          backend:
            service:
              name: {{ $fullName }}-{{ $i }}
              port:
                number: 80
      {{- end }}
        - path: {{ include "ingress.path" . }}
          pathType: Prefix
          backend:
            service:
              name: {{ $fullName }}-routing
              port:
                number: 80