{{- $fullName := include "fullName" . -}}
{{- $namespace := include "namespace" . -}}
apiVersion: traefik.io/v1alpha1
kind: ServersTransportTCP
metadata:
  name: {{ $fullName }}-transport
  namespace: {{ $namespace }}
  labels:
    helmVersion: {{ .Chart.Version }}
    helmAppVersion: {{ .Chart.AppVersion }}
    helmName: {{ .Chart.Name }}
spec:
  tls:
    insecureSkipVerify: true